### ISSUE TITLE
detect closed StreamWriter/StreamReader not working

### ISSUE THREAD

**Issue by komuw** [komuw/naz#120]
```python
import asyncio
import logging

logging.basicConfig(level=logging.DEBUG)
smsc_host = "127.0.0.1"
smsc_port = 2775

async def connect():
    reader, writer = await asyncio.wait_for(
        asyncio.open_connection(smsc_host, smsc_port), timeout=3.4
    )
    writer.transport.set_write_buffer_limits(16)
    return reader, writer


loop = asyncio.get_event_loop()
reader, writer = loop.run_until_complete(connect())

async def main():
    while True:
        print("wrtiting. witer={0}".format(writer.transport.get_protocol()._stream_writer))

        # https://github.com/aio-libs/aiohttp/issues/2499
        if writer.transport is None or writer.transport.is_closing():
            raise ConnectionResetError("Cannot write to closing transport")
        writer.write(b"msg")
        await writer.drain()

        print("wrtitten. reader={0}".format(writer.transport.get_protocol()._stream_reader))
        print("cloisng={0}".format(writer.transport.is_closing()))

        try:
            await asyncio.wait_for(reader.read(4), timeout=1.2)
        except asyncio.TimeoutError as e:
            print("\n\n\t timeout", str(e))
            print("\n")

        await asyncio.sleep(3)

loop.run_until_complete(main())
```

1. start a server at `127.0.0.1:2775`
2. run the code above
3. stop the server at `127.0.0.1:2775`
4. the code above continues running as if the server is still available.
`writer.transport.is_closing()` is supposed to tell us when/if the connection is broken but it does not.

**Comment by komuw** [comment]
this one connecting to google works
```python
import sys
import asyncio
import logging

# using python3.6
logging.basicConfig(format="%(message)s", stream=sys.stdout, level=logging.DEBUG)

async def connect():
    reader, writer = await asyncio.open_connection(host="google.com", port=80)
    writer.transport.set_write_buffer_limits(2)
    return reader, writer

async def main():
    _, writer = await connect()
    while True:
        # https://github.com/aio-libs/aiohttp/issues/2499
        if writer.transport is None or writer.transport.is_closing():
            # this should detect lost connection but it doesn't
            raise ConnectionResetError("Cannot write to closing transport")
        print("about to write")
        writer.write(b"SomeMessage")
        await writer.drain()
        print("written")
        await asyncio.sleep(4)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

1. start the code
2. kill off wifi(after killing wifi, it continues writing for a short while then raises error)
```bash
about to write
written
about to write
written
about to write
written
about to write
written
about to write
written
about to write
written

	 _read_ready called

self.max_size:  262144
self._conn_lost:  0

[Errno 60] Operation timed out
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 718, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 60] Operation timed out
Fatal read error on socket transport
protocol: <asyncio.streams.StreamReaderProtocol object at 0x103d16668>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
```

**Comment by komuw** [comment]
However the following works okay:
```python
import asyncio

async def connect():
    reader, writer = await asyncio.open_connection(host="127.0.0.1", port=8000)
    return reader, writer

async def main():
    _, writer = await connect()
    while True:
        # https://github.com/aio-libs/aiohttp/issues/2499
        if writer.transport is None or writer.transport.is_closing():
            # this should detect lost connection but it doesn't
            raise ConnectionResetError("Cannot write to closing transport")

        print("about to write")
        writer.write(b"SomeMessage")
        await writer.drain()
        print("written")
        await asyncio.sleep(1)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

1. start a python server on localhost
`python2 -m SimpleHTTPServer 8000`
2. run the code above
3. kill the python server
```bash
about to write
written
about to write
written
about to write
written
about to write
written
about to write
written
about to write
Traceback (most recent call last):
  File "cool.py", line 26, in <module>
    loop.run_until_complete(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "cool.py", line 19, in main
    await writer.drain()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/streams.py", line 337, in drain
    yield from self._protocol._drain_helper()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/streams.py", line 211, in _drain_helper
    raise ConnectionResetError("Connection lost")
ConnectionResetError: Connection lost
```

**Comment by komuw** [comment]
I'm beginning to supect that the difference between the example above that works(using SimpleHTTPServer) and the ones that do not is that those that do not are talking to a server running in docker. 
And when we kill that docker container, our code is left with a connection open to the docker_proxy thing that is setup by docker/docker-compose. So our code still thinks it is still connected to the real server

**Comment by komuw** [comment]
for the docker examples, if you restart docker itself; I'm able to get a ConnectionResetError
