### ISSUE TITLE
handle all socket timeouts

### ISSUE THREAD

**Issue by komuw** [komuw/naz#140]
found via benchmarking

```bash
naz_cli             | 2019-06-12 17:10:05,821
naz_cli             |
naz_cli             | 	 Naz: the SMPP client.
naz_cli             |
naz_cli             |
naz_cli             | {'timestamp': '2019-06-12 17:10:05,821', 'event': 'naz.cli.main', 'stage': 'start', 'client_id': 'HQ0G8YK4ZUIF0887P'}
naz_cli             | Executing <Handle <TaskWakeupMethWrapper object at 0x7ff66c325e58>(<Future finis...events.py:295>) created at /usr/local/lib/python3.6/asyncio/futures.py:378> took 6.245 seconds
naz_cli             | Fatal write error on socket transport
naz_cli             | handle_traceback: Handle created at (most recent call last):
naz_cli             |   File "/usr/local/bin/naz-cli", line 10, in <module>
naz_cli             |     sys.exit(main())
naz_cli             |   File "/usr/local/lib/python3.6/site-packages/cli/cli.py", line 88, in main
naz_cli             |     async_main(client=client, logger=logger, loop=loop, dry_run=dry_run)
naz_cli             |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 471, in run_until_complete
naz_cli             |     self.run_forever()
naz_cli             |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
naz_cli             |     self._run_once()
naz_cli             |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1443, in _run_once
naz_cli             |     handle._run()
naz_cli             |   File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
naz_cli             |     self._callback(*self._args)
naz_cli             |   File "/usr/local/lib/python3.6/asyncio/futures.py", line 399, in _set_state
naz_cli             |     _copy_future_state(other, future)
naz_cli             |   File "/usr/local/lib/python3.6/asyncio/futures.py", line 378, in _copy_future_state
naz_cli             |     dest.set_result(result)
naz_cli             | protocol: <asyncio.streams.StreamReaderProtocol object at 0x7ff66c26f2b0>
naz_cli             | transport: <_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>
naz_cli             | Traceback (most recent call last):
naz_cli             |   File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 752, in write
naz_cli             |     n = self._sock.send(data)
naz_cli             | socket.timeout: timed out
naz_cli             | Executing <Handle <TaskWakeupMethWrapper object at 0x7ff66c325588>(<Future finis...events.py:295>) created at /usr/local/lib/python3.6/asyncio/futures.py:378> took 15.011 seconds
naz_cli             | {'timestamp': '2019-06-12 18:59:49,447', 'event': 'naz.cli.main', 'stage': 'end', 'error': 'timed out'}
naz_cli             | Traceback (most recent call last):
naz_cli             |   File "/usr/local/lib/python3.6/site-packages/cli/cli.py", line 88, in main
naz_cli             |     async_main(client=client, logger=logger, loop=loop, dry_run=dry_run)
naz_cli             |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
naz_cli             |     return future.result()
naz_cli             |   File "/usr/local/lib/python3.6/site-packages/cli/cli.py", line 115, in async_main
naz_cli             |     await tasks
naz_cli             |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 129, in throw
naz_cli             |     return self.gen.throw(type, value, traceback)
naz_cli             |   File "/usr/local/lib/python3.6/site-packages/naz/client.py", line 1819, in receive_data
naz_cli             |     command_length_header_data = await self.reader.read(4)
naz_cli             |   File "/usr/local/lib/python3.6/asyncio/streams.py", line 634, in read
naz_cli             |     yield from self._wait_for_data('read')
naz_cli             |   File "/usr/local/lib/python3.6/asyncio/streams.py", line 464, in _wait_for_data
naz_cli             |     yield from self._waiter
naz_cli             |   File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 752, in write
naz_cli             |     n = self._sock.send(data)
naz_cli             | socket.timeout: timed out
naz_cli             | {'timestamp': '2019-06-12 18:59:49,448', 'event': 'naz.cli.main', 'stage': 'end'}
naz_cli exited with code 77
```

**Comment by komuw** [comment]
everything here; https://docs.python.org/3.6/library/socket.html#exceptions needs to be catered for
