### ISSUE TITLE
add ability to start `naz` even when SMSC is down

### ISSUE THREAD

**Issue by komuw** [komuw/naz#167]
Currently if SMSC is down and you start `naz`;      

`naz-cli --client examples.example_config.client`
```bash
2019-09-17 10:27:03,609

	 Naz: the SMPP client.


{'timestamp': '2019-09-17 10:27:03,609', 'event': 'naz.cli.main', 'stage': 'start', 'client_id': '4H65TZF2ZO2DNFJ5Z'}
{'timestamp': '2019-09-17 10:27:03,623', 'event': 'naz.Client.connect', 'stage': 'start', 'log_id': 'or3dti786xziup30i', 'environment': 'staging', 'release': 'canary', 'smsc_host': '127.0.0.1', 'system_id': 'smppclient1', 'client_id': 'WKPMAS0RI9JBKY683', 'pid': 93206}
{'timestamp': '2019-09-17 10:27:03,624', 'event': 'naz.cli.main', 'stage': 'end', 'error': "[Errno 61] Connect call failed ('127.0.0.1', 2775)"}
Traceback (most recent call last):
  File "/Users/komuw/mystuff/naz/cli/cli.py", line 92, in main
    asyncio.run(async_main(client=client, logger=logger, dry_run=dry_run), debug=asyncio_debug)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/Users/komuw/mystuff/naz/cli/cli.py", line 102, in async_main
    await client.connect()
  File "/Users/komuw/mystuff/naz/naz/client.py", line 804, in connect
    reader, writer = await asyncio.open_connection(self.smsc_host, self.smsc_port)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py", line 77, in open_connection
    lambda: protocol, host, port, **kwds)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 943, in create_connection
    raise exceptions[0]
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 930, in create_connection
    await self.sock_connect(sock, address)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py", line 475, in sock_connect
    return await fut
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 61] Connect call failed ('127.0.0.1', 2775)
{'timestamp': '2019-09-17 10:27:03,626', 'event': 'naz.cli.main', 'stage': 'end'}
```

You should however, be able to start `naz` even when the SMSC is down, and then when the SMSC comes up back again; then `naz` is able to connect and carry on as expected

**Comment by komuw** [comment]
A simple implementation of this is at; https://github.com/komuw/naz/pull/168
