### ISSUE TITLE
infinite loop of re-establishing connection

### ISSUE THREAD

**Issue by komuw** [komuw/naz#170]
If connection to SMSC fails, the logic to re-establish connection and re-bind can go into an infinite loop until the SMSC comes up. There's nothing thaat(Kenya-nglish) bad that can happen, however it can lead to generation of lots of logs since `naz.Client.re_establish_conn_bind` is getting called multiple times in a second

```bash
{'timestamp': '2019-09-22 13:35:05,987', 'event': 'naz.Client.re_establish_conn_bind', 'stage': 'start', 'smpp_command': 'enquire_link', 'log_id': 't2ocbn8cb0aypdipx', 'connection_lost': True, 'environment': 'staging', 'release': 'canary', 'smsc_host': '127.0.0.1', 'system_id': 'smppclient1', 'client_id': '7ESEUIJX5WYKDT1NR', 'pid': 8727}
{'timestamp': '2019-09-22 13:35:05,987', 'event': 'naz.Client.connect', 'stage': 'start', 'log_id': 't2ocbn8cb0aypdipx', 'environment': 'staging', 'release': 'canary', 'smsc_host': '127.0.0.1', 'system_id': 'smppclient1', 'client_id': '7ESEUIJX5WYKDT1NR', 'pid': 8727}
{'timestamp': '2019-09-22 13:35:05,987', 'event': 'naz.Client.connect', 'stage': 'end', 'log_id': 't2ocbn8cb0aypdipx', 'error': "[Errno 111] Connect call failed ('127.0.0.1', 2775)", 'environment': 'staging', 'release': 'canary', 'smsc_host': '127.0.0.1', 'system_id': 'smppclient1', 'client_id': '7ESEUIJX5WYKDT1NR', 'pid': 8727}
Traceback (most recent call last):
  File "/home/stuff/mystuff/naz/naz/client.py", line 810, in connect
    reader, writer = await asyncio.open_connection(self.smsc_host, self.smsc_port)
  File "/usr/lib/python3.7/asyncio/streams.py", line 77, in open_connection
    lambda: protocol, host, port, **kwds)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 959, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.7/asyncio/base_events.py", line 946, in create_connection
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
    return await fut
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 494, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 2775)
{'timestamp': '2019-09-22 13:35:05,988', 'event': 'naz.Client.tranceiver_bind', 'stage': 'start', 'log_id': 't2ocbn8cb0aypdipx', 'smpp_command': 'bind_transceiver', 'environment': 'staging', 'release': 'canary', 'smsc_host': '127.0.0.1', 'system_id': 'smppclient1', 'client_id': '7ESEUIJX5WYKDT1NR', 'pid': 8727}
{'timestamp': '2019-09-22 13:35:05,988', 'event': 'naz.Client.send_data', 'stage': 'start', 'smpp_command': 'bind_transceiver', 'log_id': 't2ocbn8cb0aypdipx', 'msg': '@@@8@@@Ç@@@@@@@ìsmppclient1@{REDACTED}@@@@@"@@@@@@@@^254@', 'connection_lost': True, 'environment': 'staging', 'release': 'canary', 'smsc_host': '127.0.0.1', 'system_id': 'smppclient1', 'client_id': '7ESEUIJX5WYKDT1NR', 'pid': 8727}
{'timestamp': '2019-09-22 13:35:05,988', 'event': 'naz.Client.re_establish_conn_bind', 'stage': 'start', 'smpp_command': 'bind_transceiver', 'log_id': 't2ocbn8cb0aypdipx', 'connection_lost': True, 'environment': 'staging', 'release': 'canary', 'smsc_host': '127.0.0.1', 'system_id': 'smppclient1', 'client_id': '7ESEUIJX5WYKDT1NR', 'pid': 8727}
{'timestamp': '2019-09-22 13:35:05,988', 'event': 'naz.Client.connect', 'stage': 'start', 'log_id': 't2ocbn8cb0aypdipx', 'environment': 'staging', 'release': 'canary', 'smsc_host': '127.0.0.1', 'system_id': 'smppclient1', 'client_id': '7ESEUIJX5WYKDT1NR', 'pid': 8727}
{'timestamp': '2019-09-22 13:35:05,989', 'event': 'naz.Client.connect', 'stage': 'end', 'log_id': 't2ocbn8cb0aypdipx', 'error': "[Errno 111] Connect call failed ('127.0.0.1', 2775)", 'environment': 'staging', 'release': 'canary', 'smsc_host': '127.0.0.1', 'system_id': 'smppclient1', 'client_id': '7ESEUIJX5WYKDT1NR', 'pid': 8727}

```

**Comment by komuw** [comment]
When connection to SMSC fails;   

1. `re_establish_conn_bind` is called by `naz.Client.send_data`; https://github.com/komuw/naz/blob/592e48a89d01c3e4c0964d8e6a8ba269eac1b149/naz/client.py#L1594-L1596      

2. `re_establish_conn_bind` in turn calls `client.connect` & `client.tranceiver_bind`; https://github.com/komuw/naz/blob/592e48a89d01c3e4c0964d8e6a8ba269eac1b149/naz/client.py#L1463-L1477    

3.  `client.connect` fails since SMSC is down. however that method since a few PR's ago no longer bubbles up an error & because of this `client.tranceiver_bind` is called by `re_establish_conn_bind`. 

4. `client.tranceiver_bind` calls `client.send_data`; https://github.com/komuw/naz/blob/592e48a89d01c3e4c0964d8e6a8ba269eac1b149/naz/client.py#L919-L926 

5. go back to step 1

**Comment by komuw** [comment]
we should re-run the benchmarks
