### ISSUE TITLE
RuntimeError: Cannot call write() after write_eof()

### ISSUE THREAD

**Issue by komuw** [komuw/naz#203]
With https://github.com/komuw/naz/pull/202,  
If you have the following:  
```python
if __name__ == "__main__":
    my_broker = ExampleRedisBroker()
    loop = asyncio.get_event_loop()
    for i in range(0, 4):
        print("submit_sm round:", i)
        loop.run_until_complete(
            my_broker.enqueue(
                naz.protocol.SubmitSM(
                    short_message="Hello World-{0}".format(str(i)),
                    log_id="myid1234-{0}".format(str(i)),
                    source_addr="254722111111",
                    destination_addr="254722999999",
                    hook_metadata='{"telco": "verizon", "customer_id": 123456}',
                    user_message_reference=34,
                    # dpf_result is bad a paramter to use in a submit_sm; it should be used for data_sm
                   # we are just looking for a way to crash the smpp server in order to reproduce this bug.
                    dpf_result=1, 
                )
            )
        )
```

When you send that, the smpp server fails with:
```bash
smpp_server_1  | 2020.05.29 08:08:02 514 INFO    18 : Standard SUBMIT_SM:
smpp_server_1  | 2020.05.29 08:08:02 514 INFO    18 Hex dump (84) bytes:
smpp_server_1  | 2020.05.29 08:08:02 514 INFO    18 00000054:00000004:00000000:00000005:
smpp_server_1  | 2020.05.29 08:08:02 514 INFO    18 434D5400:01013235:34373232:31313131:
smpp_server_1  | 2020.05.29 08:08:02 515 INFO    18 31310001:01323534:37323239:39393939:
smpp_server_1  | 2020.05.29 08:08:02 515 INFO    18 39000300:00000001:0000000D:48656C6C:
smpp_server_1  | 2020.05.29 08:08:02 515 INFO    18 6F20576F:726C642D:30020400:02002204:
smpp_server_1  | 2020.05.29 08:08:02 515 INFO    18 20000201:
smpp_server_1  | 2020.05.29 08:08:02 515 INFO    18 84
smpp_server_1  | java.lang.ArrayIndexOutOfBoundsException: 84
smpp_server_1  | 	at com.seleniumsoftware.SMPPSim.pdu.SubmitSM.demarshall(Unknown Source)
smpp_server_1  | 	at com.seleniumsoftware.SMPPSim.StandardProtocolHandler.getSubmitSMResponse(Unknown Source)
smpp_server_1  | 	at com.seleniumsoftware.SMPPSim.StandardProtocolHandler.processMessage(Unknown Source)
smpp_server_1  | 	at com.seleniumsoftware.SMPPSim.StandardConnectionHandler.runThread(Unknown Source)
smpp_server_1  | 	at com.seleniumsoftware.SMPPSim.StandardConnectionHandler.run(Unknown Source)
smpp_server_1  | 	at java.lang.Thread.run(Thread.java:748)
```

And then `naz` fails with:
```python
{'timestamp': '2020-05-29 11:08:02,502', 'event': 'naz.Client.receive_data', 'stage': 'end', 'state': 'unable to read exactly 16bytes of smpp header.', 'error': '0 bytes read on a total of 16 expected bytes'}
Traceback (most recent call last):
  File "/Users/komuw/mystuff/naz/naz/client.py", line 1760, in receive_data
    header_data = await self.reader.readexactly(self._header_pdu_length)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 16 expected bytes
{'timestamp': '2020-05-29 11:08:02,503', 'event': 'naz.Client.unbind', 'stage': 'start', 'log_id': '1k4mo39p5n3920xz6', 'smpp_command': 'unbind'}
{'timestamp': '2020-05-29 11:08:02,504', 'event': 'naz.Client.send_data', 'stage': 'start', 'smpp_command': 'unbind', 'log_id': '1k4mo39p5n3920xz6', 'msg': '\x00\x00\x00\x10\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07', 'connection_lost': False}
{'timestamp': '2020-05-29 11:08:02,504', 'event': 'naz.Client.send_data', 'stage': 'end', 'smpp_command': 'unbind', 'log_id': '1k4mo39p5n3920xz6', 'msg': '\x00\x00\x00\x10\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07'}
{'timestamp': '2020-05-29 11:08:02,504', 'event': 'naz.Client.unbind', 'stage': 'end', 'log_id': '1k4mo39p5n3920xz6', 'smpp_command': 'unbind'}
{'timestamp': '2020-05-29 11:08:02,504', 'event': 'naz.Client.receive_data', 'stage': 'start', 'state': 'no data received from SMSC. sleeping for 120.00 seconds', 'retry_count': 1}
{'timestamp': '2020-05-29 11:08:02,505', 'event': 'naz.Client.send_data', 'stage': 'start', 'smpp_command': 'submit_sm', 'log_id': 'myid1234-2', 'msg': '\x00\x00\x00T\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x08CMT\x00\x01\x01254722111111\x00\x01\x01254722999999\x00\x03\x00\x00\x00\x00\x01\x00\x00\x00\rHello World-2\x02\x04\x00\x02\x00"\x04 \x00\x02\x01', 'connection_lost': False}
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py:137: RuntimeWarning: coroutine '_handle_termination_signal' was never awaited
  del self._signal_handlers[sig]
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
{"timestamp": "2020-05-29 11:08:02,508", "event": "naz.cli.main", "stage": "end", "error": "Cannot call write() after write_eof()"}
Traceback (most recent call last):
  File "/Users/komuw/mystuff/naz/cli/cli.py", line 92, in main
    asyncio.run(async_main(client=client, logger=logger, dry_run=dry_run), debug=asyncio_debug)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/komuw/mystuff/naz/cli/cli.py", line 115, in async_main
    await tasks
  File "/Users/komuw/mystuff/naz/naz/client.py", line 1673, in dequeue_messages
    hook_metadata=hook_metadata,
  File "/Users/komuw/mystuff/naz/naz/client.py", line 1495, in send_data
    self.writer.write(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py", line 305, in write
    self._transport.write(data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py", line 855, in write
    raise RuntimeError('Cannot call write() after write_eof()')
RuntimeError: Cannot call write() after write_eof()
{"timestamp": "2020-05-29 11:08:02,509", "event": "naz.cli.main", "stage": "end"}
```

**Comment by komuw** [comment]
So;
- smpp fails
- naz is unable to read complete header from smpp; https://github.com/komuw/naz/blob/52e89b9007d2e066cdc90e1b2614ac3ad96e0188/naz/client.py#L1743-L1754
- naz calls unbind_and_disconnect: https://github.com/komuw/naz/blob/52e89b9007d2e066cdc90e1b2614ac3ad96e0188/naz/client.py#L1757
- that closes the writing end of the connection: https://github.com/komuw/naz/blob/52e89b9007d2e066cdc90e1b2614ac3ad96e0188/naz/client.py#L2321-L2335  
but not the reader; see: https://github.com/komuw/naz/commit/c74983cb405052724548a3466d54ed5ae1823df8
- naz tries to write something: https://github.com/komuw/naz/blob/52e89b9007d2e066cdc90e1b2614ac3ad96e0188/naz/client.py#L1477    
this fails since we had already closed the writing end.    

The code to check if writer is closed: https://github.com/komuw/naz/blob/52e89b9007d2e066cdc90e1b2614ac3ad96e0188/naz/client.py#L1446   did not see that writer is closed because; `self.writer` is still True and `self.writer.transport.is_closing()` is False.    


We could replace `self.writer.write_eof()` with `self.writer.close()` in `unbind_and_disconnect` method. However that is not what we want, see: https://github.com/komuw/naz/commit/c74983cb405052724548a3466d54ed5ae1823df8 for explanation including the linked issue.    
An alternative would be to do; `self.writer=None` in `unbind_and_disconnect` method.

**Comment by komuw** [comment]
When we fix this; make sure not to re-introduce: https://github.com/komuw/naz/issues/197  
Add a testcase to guard against re-introduction of https://github.com/komuw/naz/issues/197 (if we do not have one already)

**Comment by komuw** [comment]
Maybe a reproducer testcase needs to just call `unbind_and_disconnect` and then call `send_data`

**Comment by komuw** [comment]
This commit: https://github.com/komuw/naz/pull/208/commits/7c9c8281c94c43ed129fb3f490cd6d8942157bd8   
reproduces the issue in a testcase; 
`python -m unittest -v tests.test_client.TestClient.test_issues_203`
```python

Traceback (most recent call last):
  File "/tmp/naz/tests/test_client.py", line 1091, in test_issues_203
    smpp_command=naz.SmppCommand.SUBMIT_SM, msg=b"someMessage", log_id="log_id"
  File "/tmp/naz/tests/test_client.py", line 75, in _run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/tmp/naz/naz/client.py", line 1502, in send_data
    self.writer.write(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py", line 305, in write
    self._transport.write(data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py", line 855, in write
    raise RuntimeError('Cannot call write() after write_eof()')
RuntimeError: Cannot call write() after write_eof()

----------------------------------------------------------------------
Ran 1 test in 1.622s

FAILED (errors=1)
```
