### ISSUE TITLE
Incorrect BIND Status for given command

### ISSUE THREAD

**Issue by komuw** [komuw/naz#52]
when we send `enquire_link`, we get such a response in `enquire_link_resp`: 

```string
{'event': 'naz.Client.speficic_handlers',  
'stage': 'start', 
'smpp_event': 'enquire_link_resp', 
'correlation_id': None,
 'command_status': 4,
 'state': 'Incorrect BIND Status for given command',
 'environment': 'myenv', 
 'smsc_host': 'host',
 'system_id': 'something', 
'client_id': 'SJeqrJJW'}
```

This usually happens if when binding to SMSC: 
- we bind as `bind_receiver` instead of `bind_transceiver`
- the bind succeds
- then we try to send data to SMSC
- SMSC is like; you guys bound as **recievers**, that binding does not allow you to send data to us.

**Comment by komuw** [comment]
search for 
```
"naz.Client.send_data" "bind_transceiver"
```
so as to see the request we sent in `bind_transceiver` request; we can then `struct.unpack` to see the "plain" data sent

**Comment by komuw** [comment]
alternatively;

 DU has been sent in the wrong session state. E.g. sending a submit_sm without first establishing a Bound_TX session state.

**Comment by komuw** [comment]
>  PDU has been sent in the wrong session state. E.g. sending a submit_sm without first establishing a Bound_TX session state. 

we will implement `2.2 SMPP Session Description/states`(section 2.2 of smpp spec v3,4) to try and guard against this

**Comment by komuw** [comment]
as of commit: https://github.com/komuw/naz/pull/63/commits/890e2bbfc6e23e990dade7bd95ccaef1f1a0fa17 

running; `naz-cli --config examples/example_config.json` produces;
```python
{'event': 'naz.cli.main', 
'stage': 'end', 
'error': 'smpp_event: enquire_link cannot be sent to SMSC when the client session state is: OPEN', 
'environment': 'staging', 
'release': 'canary', 
'smsc_host': '127.0.0.1', 
'system_id': 'smppclient1', 
'client_id': 'ZCWF2EV2N6KTVSORX'}
Traceback (most recent call last):
  File "/Users/myName/mystuff/naz/cli/cli.py", line 232, in main
    loop.run_until_complete(tasks)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/Users/myName/mystuff/naz/naz/client.py", line 454, in enquire_link
    smpp_event="enquire_link", msg=full_pdu, correlation_id=correlation_id
  File "/Users/myName/mystuff/naz/naz/client.py", line 841, in send_data
    raise ValueError(error_msg)
ValueError: smpp_event: enquire_link cannot be sent to SMSC when the client session state is: OPEN
```

which may means that we have the bug; `PDU has been sent in the wrong session state. E.g. sending a submit_sm without first establishing a Bound_TX session state.`

**Comment by komuw** [comment]
closed by; https://github.com/komuw/naz/pull/63
