### ISSUE TITLE
Connection lost on await writer.drain()

### ISSUE THREAD

**Issue by komuw** [komuw/naz#67]
This program
```python
import asyncio
import os

os.environ["PYTHONASYNCIODEBUG"] = "1"

loop = asyncio.get_event_loop()


async def client():
    reader, writer = await asyncio.open_connection("35.173.6.94", 80, loop=loop)
    print("\n connected to localhost:9881")
    while True:
        print("writer.transport._conn_lost", writer.transport._conn_lost)
        if writer.transport._conn_lost:
            writer.close()
            reader, writer = await asyncio.open_connection("35.173.6.94", 80, loop=loop)

        req = b"hello"
        writer.write(req)
        await writer.drain()
        # import pdb

        # pdb.set_trace()

        print("\nsent request\n")

        data = await reader.read(2)
        print("\n\nread:\n")
        print(data)


loop.run_until_complete(client())
```

produces the error:
```bash
read:

b''
writer.transport._conn_lost 0
Executing <Handle <TaskWakeupMethWrapper object at 0x1053433d8>(<Future finis...events.py:377>) created at /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py:408> took 1.974 seconds
Traceback (most recent call last):
  File "smpp/debug.py", line 35, in <module>
    loop.run_until_complete(client())
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "smpp/debug.py", line 23, in client
    await writer.drain()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py", line 348, in drain
    await self._protocol._drain_helper()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py", line 202, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
```

**Comment by komuw** [comment]
Applied to `naz`, we have been getting some `connection lost` errors.
```python
body = b""
command_length = 16 + len(body)  # 16 is for headers
command_id = cli.command_ids["enquire_link"]
command_status = 0x00000000
sequence_number = cli.sequence_generator.next_sequence()
header = struct.pack(">IIII", command_length, command_id, command_status, sequence_number)
full_pdu = header + body
loop.run_until_complete(
    cli.send_data(smpp_event="enquire_link", msg=full_pdu, correlation_id="correlation_id3")
)
```

error:
```bash
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/naz/client.py", line 866, in send_data
    await self.writer.drain()
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 339, in drain
    yield from self._protocol._drain_helper()
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 210, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
```

see the culprit line; https://github.com/komuw/naz/blob/f2e8312ce53ebf91b8d97f1331e0c2ce1002808d/naz/client.py#L866

**Comment by komuw** [comment]
to manually fix the issue with `naz` above, this code tries to do that:
```python
### this alone with NO `cli.tranceiver_bind`
reader, writer = loop.run_until_complete(cli.connect()) 

### make SURE the session state is the right one.
cli.current_session_state = "BOUND_TRX" 

## send `enquire_link`
loop.run_until_complete(
    cli.send_data(smpp_event="enquire_link", msg=full_pdu, correlation_id="correlation_id3")
)

## read `enquire_link_resp` and print it
full_enquire_link_resp_pdu_data = receive_data()
parsed_enquire_link_resp = parse_response_pdu(full_enquire_link_resp_pdu_data)
print("\n parsed_enquire_link_resp: \n")
print(parsed_enquire_link_resp)
```

prints
```bash
{
'correlation_id': None, 
'command_id': 2147483669, 
'command_status': 4, 
'smpp_event': 'enquire_link_resp', 
'command_status_name': 'ESME_RINVBNDSTS', 
'command_status_value': CommandStatus(code=4, description='Incorrect BIND Status for given command'), 
'command_status_code': 4, 
'command_status_value_description': 'Incorrect BIND Status for given command'
}
```

**Comment by komuw** [comment]
This manual fix, fixes that issue:
```python
### connect
reader, writer = loop.run_until_complete(cli.connect()) 

### send bind_transceiver
loop.run_until_complete(
    cli.send_data(smpp_event="bind_transceiver", msg=full_pdu, correlation_id="correlation_id1")
)
### read bind_transceiver_resp
full_tranceiver_bind_resp_pdu_data = receive_data()
parsed_tranceiver_bind_resp = parse_response_pdu(full_tranceiver_bind_resp_pdu_data)


## send `enquire_link`
loop.run_until_complete(
    cli.send_data(smpp_event="enquire_link", msg=full_pdu, correlation_id="correlation_id3")
)

## read `enquire_link_resp` and print it
full_enquire_link_resp_pdu_data = receive_data()
parsed_enquire_link_resp = parse_response_pdu(full_enquire_link_resp_pdu_data)
print("\n parsed_enquire_link_resp: \n")
print(parsed_enquire_link_resp)
```

prints
```bash
{
'correlation_id': None, 
'command_id': 2147483669, 
'command_status': 0, 
'smpp_event': 'enquire_link_resp', 
'command_status_name': 'ESME_ROK', 
'command_status_value': CommandStatus(code=0, description='Success'), 
'command_status_code': 0, 
'command_status_value_description': 'Success'
}
```

**Comment by komuw** [comment]
We need to continuously check if connection is broken(how??, maybe `cli.writer.transport._conn_lost`) and if it is;
- `cli.connect()`
- `cli.tranceiver_bind()`

**Comment by komuw** [comment]
One reason why you may experience Connection lost errors is because of session timers[1][2].        
As an example, if an SMSC has a very small `inactivity_timer`[2], then the SMSC may be closing the session(and the connection) at the expiry of that `inactivity_timer`.      

One way to workaround this, is to set a very low `enquire_link_interval` on your `naz` client;  
```python
import asyncio
import naz

loop = asyncio.get_event_loop()
outboundqueue = naz.q.SimpleOutboundQueue(maxsize=1000, loop=loop)
cli = naz.Client(
    async_loop=loop,
    smsc_host="127.0.0.1",
    smsc_port=2775,
    system_id="smppclient1",
    password="password",
    enquire_link_interval=5,
)
```
or if using the `naz` command line app;
```json
{
    "smsc_host": "127.0.0.1",
    "smsc_port": 5004,
    "system_id": "SomeID",
    "password": "somePassword",
    "enquire_link_interval": 5
}
```

where the value you chose for `enquire_link_interval` is less than the value set on SMSC of `inactivity_timer`.     

That way, the `inactivity_timer` will never be met on the SMSC side.

**ref:**
1. https://github.com/komuw/naz/issues/73   
2. see; sections 2.9 and 7.2 of SMPP specification document v3.4

**Comment by komuw** [comment]
How to reproduce, with the current head at;

1. `docker-compose up`
2. `naz-cli --config examples/example_config.json`
3. `python examples/example_klasses.py`
4. kill the smpp_server container
